apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-pilot.k8sPilotAgent.fullname" . }}
  labels:
    {{- include "kube-pilot.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - deployments
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create