apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-pilot.k8sPilotAgent.fullname" . }}
  labels:
    {{- include "kube-pilot.labels" (dict "context" . "component" .Values.k8sPilotAgent.name "name" .Values.k8sPilotAgent.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-pilot.k8sPilotAgent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-pilot.k8sPilotAgent.serviceAccountName" . }}
  namespace: {{ include "kube-pilot.namespace" . }}
