apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.k8sPilotAgent.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ include "kube-pilot.k8sPilotAgent.fullname" . }}
  namespace: {{ include  "kube-pilot.namespace" . }}
  labels:
    {{- include "kube-pilot.labels" (dict "context" . "name" .Values.k8sPilotAgent.name) | nindent 4 }}
spec:
  replicas: {{ .Values.k8sPilotAgent.replicas }}
  selector:
    matchLabels:
      {{- include "kube-pilot.selectorLabels" (dict "context" . "name" .Values.k8sPilotAgent.name) | nindent 6 }}
  template:
    metadata:
      {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.k8sPilotAgent.podAnnotations) }}
      annotations:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "kube-pilot.labels" (dict "context" . "name" .Values.k8sPilotAgent.name) | nindent 8 }}
    spec:
      {{- with .Values.k8sPilotAgent.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.k8sPilotAgent.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.k8sPilotAgent.terminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ include "kube-pilot.k8sPilotAgent.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.k8sPilotAgent.automountServiceAccountToken }}
      containers:
        - name: {{ .Values.k8sPilotAgent.name }}
          {{- with .Values.k8sPilotAgent.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ default .Values.global.image.repository .Values.k8sPilotAgent.image.repository }}:{{ default (include "kube-pilot.defaultTag" .) .Values.k8sPilotAgent.image.tag }}
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.k8sPilotAgent.image.imagePullPolicy }}
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.global.env.kafkaBroker }}
            - name: KAFKA_CREATE_DEPLOY_TOPIC
              value: {{ .Values.global.env.kafkaCreateDeployTopic }}
            - name: KAFKA_HEALTH_CHECK_TOPIC
              value: {{ .Values.global.env.kafkaHealthCheckTopic }}
          ports:
            - name: http
              containerPort: {{ .Values.k8sPilotAgent.containerPorts.http }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.k8sPilotAgent.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.k8sPilotAgent.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.k8sPilotAgent.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.k8sPilotAgent.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.k8sPilotAgent.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.k8sPilotAgent.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.k8sPilotAgent.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.k8sPilotAgent.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.k8sPilotAgent.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.k8sPilotAgent.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.k8sPilotAgent.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.k8sPilotAgent.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.k8sPilotAgent.resources | nindent 12 }}
          {{- with .Values.k8sPilotAgent.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 10 }}
          {{- end }}