apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.k8sPilotAgent.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "kube-pilot.k8sPilotAgent.serviceAccount.name" . }}
  namespace: {{ include  "kube-pilot.namespace" . }}
  labels:
    {{- include "kube-pilot.labels" (dict "context" . "component" .Values.k8sPilotAgent.name "name" .Values.k8sPilotAgent.name) | nindent 4 }}
