# -- Provide a name in place of `kube-pilot`
nameOverride: kube-pilot

global:
  image:
    tag: "v0.0.1"
    imagePullPolicy: Always

  # -- Secrets with credentials to pull images from a private registry
  imagePullSecrets: []

k8sPilotAgent:
  image:
    repository: kubepilot/k8s-pilot-agent
    tag: "v0.0.1"
    imagePullPolicy: Always
  replicas: 1
  containerPorts:
    server: 8080
  terminationGracePeriodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  resources: {}
  service:
    type: ClusterIP
    servicePortHttp: 8080
    servicePortHttpName: http
  serviceAccount:
    name: k8s-pilot-agent
    create: true
    automountServiceAccountToken: true
