# -- Provide a name in place of `kube-pilot`
nameOverride: kube-pilot

# -- String to fully override `"kube-pilot.fullname"`
fullnameOverride: ""

global:
  image:
    tag: "v0.0.1"
    imagePullPolicy: Always
  deploymentAnnotations: {}

  # -- Secrets with credentials to pull images from a private registry
  imagePullSecrets: []

k8sPilotAgent:
  name: k8s-pilot-agent
  image:
    repository: kubepilot/k8s-pilot-agent
    tag: "v0.0.1"
    imagePullPolicy: Always
  replicas: 1
  containerPorts:
    http: 8080
  terminationGracePeriodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  resources: {}
  deploymentAnnotations: {}
  service:
    type: ClusterIP
    servicePort: 8080
    servicePortName: http
  serviceAccount:
    name: k8s-pilot-agent
    create: true
    automountServiceAccountToken: true

server:
  name: server
  image:
    repository: kubepilot/server
    tag: "v0.0.1"
    imagePullPolicy: Always
  replicas: 1
  containerPorts:
    http: 8080
  terminationGracePeriodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  resources: {}
  deploymentAnnotations: {}
  service:
    type: ClusterIP
    servicePort: 8080
    servicePortName: http
