# -- Provide a name in place of `kube-pilot`
nameOverride: kube-pilot

# -- String to fully override `"kube-pilot.fullname"`
fullnameOverride: ""

global:
  image:
    tag: "v0.0.1"
    imagePullPolicy: Always
  deploymentAnnotations: {}
  podAnnotations: {}
  env:
    kafkaBroker: "kafka.confluent.svc.cluster.local:9092"
    kafkaCreateDeployTopic: "k8s.deploy.create"

  # -- Secrets with credentials to pull images from a private registry
  imagePullSecrets: []

k8sPilotAgent:
  name: k8s-pilot-agent
  image:
    repository: kubepilot/k8s-pilot-agent
    tag: "v0.0.5"
    imagePullPolicy: Always
  replicas: 1
  containerPorts:
    http: 8080
  terminationGracePeriodSeconds: 30
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  resources: {}
  deploymentAnnotations: {}
  podAnnotations: {}
  service:
    type: ClusterIP
    servicePort: 80
    servicePortName: http
  serviceAccount:
    name: k8s-pilot-agent
    create: true
    automountServiceAccountToken: true

server:
  name: server
  image:
    repository: kubepilot/server
    tag: "v0.0.10"
    imagePullPolicy: Always
  replicas: 1
  containerPorts:
    http: 3000
  terminationGracePeriodSeconds: 30
  livenessProbe:
    path: /ping
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  resources: {}
  deploymentAnnotations: {}
  podAnnotations: {}
  service:
    type: ClusterIP
    servicePort: 80
    servicePortName: http
  serviceAccount:
    create: false
    name: default
