apiVersion: v1
kind: Service
metadata:
  name: {{ template "resource-simulator.fullname" . }}
  namespace: {{ include  "resource-simulator.namespace" . }}
  labels:
    {{- include "resource-simulator.labels" (dict "context" . "name" .Values.resourceSimulator.name) | nindent 4 }}
spec:
  type: {{ .Values.resourceSimulator.service.type }}
  ports:
  - name: {{ .Values.resourceSimulator.service.servicePortName }}
    protocol: TCP
    port: {{ .Values.resourceSimulator.service.servicePort }}
    targetPort: {{ .Values.resourceSimulator.containerPorts.http }}
  selector:
    {{- include "resource-simulator.selectorLabels" (dict "context" . "name" .Values.resourceSimulator.name) | nindent 4 }}
